// Generated by https://quicktype.io
import 'dart:convert';

class CinemaModel {
  String address;
  int id;
  String name;
  String phone;

  CinemaModel({
    this.address,
    this.id,
    this.name,
    this.phone,
  });
}
