// Generated by https://quicktype.io
import 'dart:convert';

class Movies {
  List<MovieModel> items = new List();

  Movies();

  Movies.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) {
      return;
    } else {
      for (var item in jsonList) {
        final movie = new MovieModel.fromJsonMap(item);
        items.add(movie);
      }
    }
  }
}

class MovieModel {
  int id;
  String title;
  String classification;
  String trailer;
  String website;
  String releaseDate;
  String director;
  String originalLanguage;
  String sypnosys;
  String poster;
  Gender gender;

  MovieModel({
    this.id,
    this.title,
    this.classification,
    this.trailer,
    this.website,
    this.releaseDate,
    this.director,
    this.originalLanguage,
    this.sypnosys,
    this.poster,
    this.gender,
  });

  MovieModel.fromJsonMap(Map<String, dynamic> son) {
    id = son['id'];
    title = son['title'];
    classification = son['classification'];
    trailer = son['trailer'];
    website = son['website'];
    releaseDate = son['releaseDate'];
    director = son['director'];
    originalLanguage = son['originalLanguaje'];
    sypnosys = son['synopsis'];
    poster = son['poster'];
    gender = new Gender(id:(son['gender'])['id'], name: (son['gender'])['name']);
  }

  getPosterPath() {
    if (poster == null) {
      return 'https://www.pikpng.com/pngl/m/182-1822761_film-clipart-19-film-clipart-huge-freebie-download.png';
    } else {
      return poster;
    }
  }
}

class Gender {
  int id;
  String name;

  Gender({
    this.id,
    this.name,
  });
}
