// Generated by https://quicktype.io
import 'dart:convert';

/*
class Movies {
  List<MovieModel> items = new List();

  Movies();

  Movies.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) {
      return;
    } else {
      for (var item in jsonList) {
        final movie = new MovieModel.fromJsonMap(item);
        items.add(movie);
      }
    }
  }
}
*/

class Movie {
  String id;
  String titulo;
  String portada;
  String descripcion;
  String duracion;
  String idioma;
  String genero;
  String sala;
  var horarios;
  Map actor;

  Movie(
      {this.id,
      this.titulo,
      this.portada,
      this.descripcion,
      this.duracion,
      this.idioma,
      this.genero,
      this.sala,
      this.horarios,
      this.actor});

/*
  MovieModel.fromJsonMap(Map<String, dynamic> son) {
    id = son['id'];
    titulo = son['titulo'];
    portada = son['portada'];
    descripcion = son['descripcion'];
    duracion = son['duracion'];
    idioma = son['idioma'];
    genero = son['genero'];
    new Sala = son['sala'];
        new Gender(id: (son['gender'])['id'], name: (son['gender'])['name']);
  }

  getPosterPath() {
    if (poster == null) {
      return 'https://www.pikpng.com/pngl/m/182-1822761_film-clipart-19-film-clipart-huge-freebie-download.png';
    } else {
      return poster;
    }
  }
}

class Gender {
  int id;
  String name;

  Gender({
    this.id,
    this.name,
  });

  */

}
