// Generated by https://quicktype.io

class PersonModel {
  String address;
  int id;
  String lastname;
  String mail;
  String name;
  String phone;

  PersonModel({
    this.address,
    this.id,
    this.lastname,
    this.mail,
    this.name,
    this.phone,
  });
}
